// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Metro.proto

package metro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Signal_Control int32

const (
	Signal_NOT_USED  Signal_Control = 0
	Signal_START     Signal_Control = 1
	Signal_TERMINATE Signal_Control = 2
	Signal_FORWARDED Signal_Control = 3
	Signal_MESSAGE   Signal_Control = 4
	Signal_BLOCKED   Signal_Control = 5
)

var Signal_Control_name = map[int32]string{
	0: "NOT_USED",
	1: "START",
	2: "TERMINATE",
	3: "FORWARDED",
	4: "MESSAGE",
	5: "BLOCKED",
}
var Signal_Control_value = map[string]int32{
	"NOT_USED":  0,
	"START":     1,
	"TERMINATE": 2,
	"FORWARDED": 3,
	"MESSAGE":   4,
	"BLOCKED":   5,
}

func (x Signal_Control) String() string {
	return proto.EnumName(Signal_Control_name, int32(x))
}
func (Signal_Control) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{6, 0}
}

type Station struct {
	// flow id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{0}
}
func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (dst *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(dst, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Token struct {
	// container id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{1}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{2}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type StartRequest struct {
	// required(image)
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{3}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *StartRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type LinkRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// required(id, name)
	Src *Station `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// required(name, image)
	Dst                  *Station `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkRequest) Reset()         { *m = LinkRequest{} }
func (m *LinkRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()    {}
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{4}
}
func (m *LinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRequest.Unmarshal(m, b)
}
func (m *LinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRequest.Marshal(b, m, deterministic)
}
func (dst *LinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRequest.Merge(dst, src)
}
func (m *LinkRequest) XXX_Size() int {
	return xxx_messageInfo_LinkRequest.Size(m)
}
func (m *LinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRequest proto.InternalMessageInfo

func (m *LinkRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *LinkRequest) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *LinkRequest) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

type TransmitRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// required(id, name)
	Src *Station `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// required(name, image)
	Dst                  *Station `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitRequest) Reset()         { *m = TransmitRequest{} }
func (m *TransmitRequest) String() string { return proto.CompactTextString(m) }
func (*TransmitRequest) ProtoMessage()    {}
func (*TransmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{5}
}
func (m *TransmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitRequest.Unmarshal(m, b)
}
func (m *TransmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitRequest.Marshal(b, m, deterministic)
}
func (dst *TransmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitRequest.Merge(dst, src)
}
func (m *TransmitRequest) XXX_Size() int {
	return xxx_messageInfo_TransmitRequest.Size(m)
}
func (m *TransmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitRequest proto.InternalMessageInfo

func (m *TransmitRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TransmitRequest) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *TransmitRequest) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *TransmitRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Signal struct {
	Src                  *Station       `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  *Station       `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Message              string         `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Control              Signal_Control `protobuf:"varint,5,opt,name=control,proto3,enum=metro.Signal_Control" json:"control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3b7e002a18aca434, []int{6}
}
func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (dst *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(dst, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

func (m *Signal) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Signal) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Signal) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Signal) GetControl() Signal_Control {
	if m != nil {
		return m.Control
	}
	return Signal_NOT_USED
}

func init() {
	proto.RegisterType((*Station)(nil), "metro.Station")
	proto.RegisterType((*Token)(nil), "metro.Token")
	proto.RegisterType((*Status)(nil), "metro.Status")
	proto.RegisterType((*StartRequest)(nil), "metro.StartRequest")
	proto.RegisterType((*LinkRequest)(nil), "metro.LinkRequest")
	proto.RegisterType((*TransmitRequest)(nil), "metro.TransmitRequest")
	proto.RegisterType((*Signal)(nil), "metro.Signal")
	proto.RegisterEnum("metro.Signal_Control", Signal_Control_name, Signal_Control_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetroClient is the client API for Metro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetroClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Status, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Status, error)
	Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*Status, error)
	Listen(ctx context.Context, in *Token, opts ...grpc.CallOption) (Metro_ListenClient, error)
}

type metroClient struct {
	cc *grpc.ClientConn
}

func NewMetroClient(cc *grpc.ClientConn) MetroClient {
	return &metroClient{cc}
}

func (c *metroClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Metro/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metroClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Metro/Link", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metroClient) Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Metro/Transmit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metroClient) Listen(ctx context.Context, in *Token, opts ...grpc.CallOption) (Metro_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Metro_serviceDesc.Streams[0], "/metro.Metro/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &metroListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Metro_ListenClient interface {
	Recv() (*Signal, error)
	grpc.ClientStream
}

type metroListenClient struct {
	grpc.ClientStream
}

func (x *metroListenClient) Recv() (*Signal, error) {
	m := new(Signal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetroServer is the server API for Metro service.
type MetroServer interface {
	Start(context.Context, *StartRequest) (*Status, error)
	Link(context.Context, *LinkRequest) (*Status, error)
	Transmit(context.Context, *TransmitRequest) (*Status, error)
	Listen(*Token, Metro_ListenServer) error
}

func RegisterMetroServer(s *grpc.Server, srv MetroServer) {
	s.RegisterService(&_Metro_serviceDesc, srv)
}

func _Metro_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetroServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Metro/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetroServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metro_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetroServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Metro/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetroServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metro_Transmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetroServer).Transmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Metro/Transmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetroServer).Transmit(ctx, req.(*TransmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metro_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Token)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetroServer).Listen(m, &metroListenServer{stream})
}

type Metro_ListenServer interface {
	Send(*Signal) error
	grpc.ServerStream
}

type metroListenServer struct {
	grpc.ServerStream
}

func (x *metroListenServer) Send(m *Signal) error {
	return x.ServerStream.SendMsg(m)
}

var _Metro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metro.Metro",
	HandlerType: (*MetroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Metro_Start_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _Metro_Link_Handler,
		},
		{
			MethodName: "Transmit",
			Handler:    _Metro_Transmit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Metro_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Metro.proto",
}

func init() { proto.RegisterFile("Metro.proto", fileDescriptor_Metro_3b7e002a18aca434) }

var fileDescriptor_Metro_3b7e002a18aca434 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x51, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xac, 0xdd, 0x8c, 0xd3, 0x60, 0x0d, 0x50, 0x2c, 0xc4, 0x47, 0xb4, 0x5f, 0x41,
	0x88, 0x80, 0xd2, 0x13, 0x84, 0xd8, 0xa0, 0x8a, 0xa4, 0x41, 0x6b, 0x23, 0x24, 0x7e, 0x90, 0x89,
	0x57, 0x95, 0xd5, 0xda, 0x0b, 0xde, 0xf5, 0x49, 0x38, 0x12, 0x47, 0xe2, 0x02, 0x68, 0x27, 0x36,
	0x6d, 0x14, 0xf8, 0xa4, 0x7f, 0x7e, 0xf3, 0x66, 0xe7, 0xbd, 0xdd, 0x79, 0x06, 0x7f, 0x23, 0x4d,
	0xad, 0xe6, 0xdf, 0x6a, 0x65, 0x14, 0xb2, 0xd2, 0x02, 0xbe, 0x02, 0x2f, 0x31, 0x99, 0x29, 0x54,
	0x85, 0x13, 0xe8, 0x17, 0x79, 0xe8, 0x4c, 0x9d, 0xd9, 0x48, 0xf4, 0x8b, 0x1c, 0x11, 0x86, 0x55,
	0x56, 0xca, 0xb0, 0x4f, 0x15, 0xfa, 0xc6, 0x47, 0xc0, 0x8a, 0x32, 0xbb, 0x92, 0xe1, 0x80, 0x8a,
	0x7b, 0xc0, 0x9f, 0x00, 0x4b, 0xd5, 0xb5, 0x3c, 0x1a, 0xc1, 0x9f, 0x81, 0x6b, 0xa7, 0x37, 0xda,
	0x0e, 0xdb, 0xa9, 0x5c, 0x12, 0xc7, 0x04, 0x7d, 0xf3, 0x0f, 0x30, 0x4e, 0x4c, 0x56, 0x1b, 0x21,
	0xbf, 0x37, 0x52, 0x1b, 0x9c, 0x81, 0xa7, 0xf7, 0x5e, 0x48, 0xd3, 0x5f, 0x4c, 0xe6, 0x64, 0x72,
	0xde, 0x3a, 0x14, 0x1d, 0x8d, 0x67, 0xe0, 0x36, 0x5a, 0xd6, 0x17, 0x51, 0xeb, 0xa3, 0x45, 0xbc,
	0x01, 0x7f, 0x5d, 0x54, 0xd7, 0xdd, 0x40, 0x0e, 0xcc, 0x58, 0x5f, 0xa4, 0xea, 0x2f, 0xc6, 0xed,
	0x38, 0xf2, 0x2a, 0xf6, 0x14, 0x4e, 0x61, 0xa0, 0xeb, 0xdd, 0x3f, 0x04, 0x2d, 0x65, 0x3b, 0x72,
	0x6d, 0x48, 0xe9, 0x2f, 0x1d, 0xb9, 0x36, 0xfc, 0x87, 0x03, 0x0f, 0xd2, 0x3a, 0xab, 0x74, 0x59,
	0x98, 0x7b, 0xd6, 0xc6, 0x10, 0xbc, 0x52, 0x6a, 0x6d, 0x77, 0x32, 0xa4, 0xb7, 0xe8, 0x20, 0xff,
	0xe5, 0x80, 0x9b, 0x14, 0x57, 0x55, 0x76, 0xf3, 0x7f, 0x85, 0xf0, 0x15, 0x78, 0x3b, 0x55, 0x99,
	0x5a, 0xdd, 0x84, 0x6c, 0xea, 0xcc, 0x26, 0x8b, 0xc7, 0xdd, 0x79, 0x52, 0x9f, 0xaf, 0xf6, 0xa4,
	0xe8, 0xba, 0xf8, 0x67, 0xf0, 0xda, 0x1a, 0x8e, 0xe1, 0xe4, 0x72, 0x9b, 0x7e, 0xf9, 0x98, 0xc4,
	0x51, 0xd0, 0xc3, 0x11, 0xb0, 0x24, 0x5d, 0x8a, 0x34, 0x70, 0xf0, 0x14, 0x46, 0x69, 0x2c, 0x36,
	0x17, 0x97, 0xcb, 0x34, 0x0e, 0xfa, 0x16, 0xbe, 0xdd, 0x8a, 0x4f, 0x4b, 0x11, 0xc5, 0x51, 0x30,
	0x40, 0x1f, 0xbc, 0x4d, 0x9c, 0x24, 0xcb, 0x77, 0x71, 0x30, 0xb4, 0xe0, 0xcd, 0x7a, 0xbb, 0x7a,
	0x1f, 0x47, 0x01, 0x5b, 0xfc, 0x74, 0x80, 0x51, 0xce, 0xf1, 0x25, 0x30, 0x8a, 0x17, 0x3e, 0xbc,
	0xbd, 0xce, 0x9f, 0xb0, 0x3d, 0x3d, 0xbd, 0x73, 0xc7, 0x46, 0xf3, 0x1e, 0xbe, 0x80, 0xa1, 0xcd,
	0x0e, 0x62, 0x4b, 0xdc, 0x09, 0xd2, 0x71, 0xf3, 0x39, 0x9c, 0x74, 0x0b, 0xc7, 0xb3, 0x6e, 0xb5,
	0x87, 0x09, 0x38, 0x3e, 0xf4, 0x1c, 0xdc, 0x75, 0xa1, 0x8d, 0xac, 0xf0, 0x20, 0x0d, 0xb7, 0x8d,
	0xf4, 0x5c, 0xbc, 0xf7, 0xda, 0xf9, 0xea, 0xd2, 0x4f, 0x7a, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x49, 0xe7, 0x3f, 0x4a, 0xb3, 0x03, 0x00, 0x00,
}
