// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Metro.proto

package metro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_FAIL StatusCode = 0
	StatusCode_OK   StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "FAIL",
	1: "OK",
}
var StatusCode_value = map[string]int32{
	"FAIL": 0,
	"OK":   1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{0}
}

type Station struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{0}
}
func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (dst *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(dst, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Token struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{1}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Status struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=metro.StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{2}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_FAIL
}

type LinkRequest struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkRequest) Reset()         { *m = LinkRequest{} }
func (m *LinkRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()    {}
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{3}
}
func (m *LinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRequest.Unmarshal(m, b)
}
func (m *LinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRequest.Marshal(b, m, deterministic)
}
func (dst *LinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRequest.Merge(dst, src)
}
func (m *LinkRequest) XXX_Size() int {
	return xxx_messageInfo_LinkRequest.Size(m)
}
func (m *LinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRequest proto.InternalMessageInfo

func (m *LinkRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *LinkRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

type TransmitRequest struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitRequest) Reset()         { *m = TransmitRequest{} }
func (m *TransmitRequest) String() string { return proto.CompactTextString(m) }
func (*TransmitRequest) ProtoMessage()    {}
func (*TransmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{4}
}
func (m *TransmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitRequest.Unmarshal(m, b)
}
func (m *TransmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitRequest.Marshal(b, m, deterministic)
}
func (dst *TransmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitRequest.Merge(dst, src)
}
func (m *TransmitRequest) XXX_Size() int {
	return xxx_messageInfo_TransmitRequest.Size(m)
}
func (m *TransmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitRequest proto.InternalMessageInfo

func (m *TransmitRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TransmitRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *TransmitRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Signal struct {
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_Metro_3a2f51a925964d3b, []int{5}
}
func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (dst *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(dst, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

func (m *Signal) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *Signal) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Station)(nil), "metro.Station")
	proto.RegisterType((*Token)(nil), "metro.Token")
	proto.RegisterType((*Status)(nil), "metro.Status")
	proto.RegisterType((*LinkRequest)(nil), "metro.LinkRequest")
	proto.RegisterType((*TransmitRequest)(nil), "metro.TransmitRequest")
	proto.RegisterType((*Signal)(nil), "metro.Signal")
	proto.RegisterEnum("metro.StatusCode", StatusCode_name, StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetroClient is the client API for Metro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetroClient interface {
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Status, error)
	Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*Status, error)
	Listen(ctx context.Context, in *Token, opts ...grpc.CallOption) (Metro_ListenClient, error)
}

type metroClient struct {
	cc *grpc.ClientConn
}

func NewMetroClient(cc *grpc.ClientConn) MetroClient {
	return &metroClient{cc}
}

func (c *metroClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Metro/Link", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metroClient) Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Metro/Transmit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metroClient) Listen(ctx context.Context, in *Token, opts ...grpc.CallOption) (Metro_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Metro_serviceDesc.Streams[0], "/metro.Metro/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &metroListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Metro_ListenClient interface {
	Recv() (*Signal, error)
	grpc.ClientStream
}

type metroListenClient struct {
	grpc.ClientStream
}

func (x *metroListenClient) Recv() (*Signal, error) {
	m := new(Signal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetroServer is the server API for Metro service.
type MetroServer interface {
	Link(context.Context, *LinkRequest) (*Status, error)
	Transmit(context.Context, *TransmitRequest) (*Status, error)
	Listen(*Token, Metro_ListenServer) error
}

func RegisterMetroServer(s *grpc.Server, srv MetroServer) {
	s.RegisterService(&_Metro_serviceDesc, srv)
}

func _Metro_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetroServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Metro/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetroServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metro_Transmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetroServer).Transmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Metro/Transmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetroServer).Transmit(ctx, req.(*TransmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metro_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Token)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetroServer).Listen(m, &metroListenServer{stream})
}

type Metro_ListenServer interface {
	Send(*Signal) error
	grpc.ServerStream
}

type metroListenServer struct {
	grpc.ServerStream
}

func (x *metroListenServer) Send(m *Signal) error {
	return x.ServerStream.SendMsg(m)
}

var _Metro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metro.Metro",
	HandlerType: (*MetroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Link",
			Handler:    _Metro_Link_Handler,
		},
		{
			MethodName: "Transmit",
			Handler:    _Metro_Transmit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Metro_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Metro.proto",
}

func init() { proto.RegisterFile("Metro.proto", fileDescriptor_Metro_3a2f51a925964d3b) }

var fileDescriptor_Metro_3a2f51a925964d3b = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x5f, 0x4b, 0xb4, 0x40,
	0x14, 0xc6, 0xd5, 0xd7, 0x3f, 0xfb, 0x1e, 0xcb, 0xb6, 0x43, 0x94, 0x74, 0x11, 0x31, 0x10, 0x6c,
	0x05, 0x16, 0xfa, 0x09, 0x22, 0x08, 0x22, 0x23, 0x70, 0xf7, 0xae, 0x2b, 0xcb, 0x61, 0x19, 0x36,
	0x67, 0xca, 0x99, 0xbd, 0xe8, 0x7b, 0xf4, 0x81, 0xc3, 0xa3, 0xb2, 0x2b, 0xdd, 0xd6, 0x9d, 0xc7,
	0xc7, 0xe7, 0x79, 0xc6, 0xdf, 0x19, 0x08, 0x1f, 0xb9, 0x69, 0x54, 0xf2, 0xde, 0x28, 0xa3, 0xd0,
	0xab, 0xdb, 0x81, 0x65, 0x10, 0xcc, 0x4d, 0x69, 0x84, 0x92, 0x88, 0xe0, 0xca, 0xb2, 0xe6, 0xb1,
	0x7d, 0x6a, 0xcf, 0xfe, 0x17, 0xf4, 0x8c, 0x07, 0xe0, 0x89, 0xba, 0x5c, 0xf2, 0xd8, 0xa1, 0x97,
	0xdd, 0xc0, 0x8e, 0xc0, 0x5b, 0xa8, 0x15, 0x97, 0x18, 0x81, 0x23, 0xaa, 0xde, 0xe0, 0x88, 0x8a,
	0x5d, 0x81, 0xdf, 0xa6, 0xad, 0x35, 0x9e, 0x81, 0xfb, 0xaa, 0xaa, 0x2e, 0x2c, 0x4a, 0xf7, 0x13,
	0x6a, 0x4b, 0x3a, 0xf1, 0x56, 0x55, 0xbc, 0x20, 0x99, 0x3d, 0x43, 0x98, 0x0b, 0xb9, 0x2a, 0xf8,
	0xc7, 0x9a, 0x6b, 0x83, 0x0c, 0x3c, 0xd3, 0x06, 0x93, 0x2d, 0x4c, 0x77, 0x7a, 0x1b, 0x95, 0x15,
	0x9d, 0x84, 0x33, 0x08, 0x74, 0x77, 0x62, 0x3a, 0x54, 0x98, 0x46, 0x5b, 0xe1, 0x42, 0xc9, 0x62,
	0x90, 0xd9, 0x27, 0xec, 0x2d, 0x9a, 0x52, 0xea, 0x5a, 0x98, 0x3f, 0x29, 0xc0, 0x18, 0x82, 0x9a,
	0x6b, 0xdd, 0xf2, 0xf9, 0x47, 0x0c, 0x86, 0x91, 0xe5, 0xe0, 0xcf, 0xc5, 0x52, 0x96, 0x6f, 0xbf,
	0x91, 0x76, 0x71, 0x02, 0xb0, 0x21, 0x87, 0x13, 0x70, 0xef, 0x6e, 0xee, 0xf3, 0xa9, 0x85, 0x3e,
	0x38, 0x4f, 0x0f, 0x53, 0x3b, 0xfd, 0xb2, 0xc1, 0xa3, 0xdd, 0xe2, 0x25, 0xb8, 0x2d, 0x4f, 0xc4,
	0xbe, 0x64, 0x0b, 0xee, 0xf1, 0xee, 0x68, 0x09, 0xcc, 0xc2, 0x0c, 0x26, 0x03, 0x1f, 0x3c, 0x1c,
	0x48, 0x8c, 0x81, 0xfd, 0x34, 0x9d, 0x83, 0x9f, 0x0b, 0x6d, 0xb8, 0xc4, 0x11, 0xbc, 0xcd, 0x87,
	0xf4, 0xdb, 0xcc, 0xba, 0xb6, 0x5f, 0x7c, 0xba, 0x69, 0xd9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0xc6, 0xb7, 0xbc, 0x78, 0x02, 0x00, 0x00,
}
