// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Router.proto

package metro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Signal_Control int32

const (
	Signal_NOT_USED  Signal_Control = 0
	Signal_START     Signal_Control = 1
	Signal_TERMINATE Signal_Control = 2
	Signal_LINKED    Signal_Control = 3
	Signal_MESSAGE   Signal_Control = 4
	Signal_BLOCKED   Signal_Control = 5
)

var Signal_Control_name = map[int32]string{
	0: "NOT_USED",
	1: "START",
	2: "TERMINATE",
	3: "LINKED",
	4: "MESSAGE",
	5: "BLOCKED",
}
var Signal_Control_value = map[string]int32{
	"NOT_USED":  0,
	"START":     1,
	"TERMINATE": 2,
	"LINKED":    3,
	"MESSAGE":   4,
	"BLOCKED":   5,
}

func (x Signal_Control) String() string {
	return proto.EnumName(Signal_Control_name, int32(x))
}
func (Signal_Control) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{5, 0}
}

type Token struct {
	// container id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{0}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StartRequest struct {
	// required(image)
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{1}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *StartRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type LinkRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// required(id, name)
	Src *Station `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// required(name, image)
	Dst                  *Station `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkRequest) Reset()         { *m = LinkRequest{} }
func (m *LinkRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()    {}
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{2}
}
func (m *LinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRequest.Unmarshal(m, b)
}
func (m *LinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRequest.Marshal(b, m, deterministic)
}
func (dst *LinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRequest.Merge(dst, src)
}
func (m *LinkRequest) XXX_Size() int {
	return xxx_messageInfo_LinkRequest.Size(m)
}
func (m *LinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRequest proto.InternalMessageInfo

func (m *LinkRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *LinkRequest) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *LinkRequest) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *LinkRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BlockRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// required(id, name)
	Src *Station `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// required(name, image)
	Dst                  *Station `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{3}
}
func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (dst *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(dst, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *BlockRequest) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *BlockRequest) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *BlockRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TransmitRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// required(id, name)
	Src *Station `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// required(name, image)
	Dst                  *Station `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitRequest) Reset()         { *m = TransmitRequest{} }
func (m *TransmitRequest) String() string { return proto.CompactTextString(m) }
func (*TransmitRequest) ProtoMessage()    {}
func (*TransmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{4}
}
func (m *TransmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitRequest.Unmarshal(m, b)
}
func (m *TransmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitRequest.Marshal(b, m, deterministic)
}
func (dst *TransmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitRequest.Merge(dst, src)
}
func (m *TransmitRequest) XXX_Size() int {
	return xxx_messageInfo_TransmitRequest.Size(m)
}
func (m *TransmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitRequest proto.InternalMessageInfo

func (m *TransmitRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TransmitRequest) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *TransmitRequest) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *TransmitRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// required                 src dst msg
// for control=START,        n   y   n
// for control=LINKED,       y   y   n
// for control=MESSAGE       y   y   o
type Signal struct {
	// required(id, name, image)
	Src *Station `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// required(id, name, image)
	Dst                  *Station       `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Message              string         `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Control              Signal_Control `protobuf:"varint,5,opt,name=control,proto3,enum=metro.Signal_Control" json:"control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_Router_e69314eab75fdaf9, []int{5}
}
func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (dst *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(dst, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

func (m *Signal) GetSrc() *Station {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Signal) GetDst() *Station {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Signal) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Signal) GetControl() Signal_Control {
	if m != nil {
		return m.Control
	}
	return Signal_NOT_USED
}

func init() {
	proto.RegisterType((*Token)(nil), "metro.Token")
	proto.RegisterType((*StartRequest)(nil), "metro.StartRequest")
	proto.RegisterType((*LinkRequest)(nil), "metro.LinkRequest")
	proto.RegisterType((*BlockRequest)(nil), "metro.BlockRequest")
	proto.RegisterType((*TransmitRequest)(nil), "metro.TransmitRequest")
	proto.RegisterType((*Signal)(nil), "metro.Signal")
	proto.RegisterEnum("metro.Signal_Control", Signal_Control_name, Signal_Control_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Status, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Status, error)
	Block(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*Status, error)
	Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*Status, error)
	Listen(ctx context.Context, in *Token, opts ...grpc.CallOption) (Router_ListenClient, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Router/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Router/Link", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Block(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Router/Block", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Router/Transmit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Listen(ctx context.Context, in *Token, opts ...grpc.CallOption) (Router_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Router_serviceDesc.Streams[0], "/metro.Router/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &routerListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Router_ListenClient interface {
	Recv() (*Signal, error)
	grpc.ClientStream
}

type routerListenClient struct {
	grpc.ClientStream
}

func (x *routerListenClient) Recv() (*Signal, error) {
	m := new(Signal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	Start(context.Context, *StartRequest) (*Status, error)
	Link(context.Context, *LinkRequest) (*Status, error)
	Block(context.Context, *BlockRequest) (*Status, error)
	Transmit(context.Context, *TransmitRequest) (*Status, error)
	Listen(*Token, Router_ListenServer) error
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Router/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Router/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Block_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Block(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Router/Block",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Block(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Transmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Transmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Router/Transmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Transmit(ctx, req.(*TransmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Token)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouterServer).Listen(m, &routerListenServer{stream})
}

type Router_ListenServer interface {
	Send(*Signal) error
	grpc.ServerStream
}

type routerListenServer struct {
	grpc.ServerStream
}

func (x *routerListenServer) Send(m *Signal) error {
	return x.ServerStream.SendMsg(m)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metro.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Router_Start_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _Router_Link_Handler,
		},
		{
			MethodName: "Block",
			Handler:    _Router_Block_Handler,
		},
		{
			MethodName: "Transmit",
			Handler:    _Router_Transmit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Router_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Router.proto",
}

func init() { proto.RegisterFile("Router.proto", fileDescriptor_Router_e69314eab75fdaf9) }

var fileDescriptor_Router_e69314eab75fdaf9 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x26, 0x59, 0xbb, 0x99, 0xb8, 0xc1, 0x1a, 0x44, 0xb1, 0x7a, 0x8a, 0xf6, 0x14, 0x84,
	0x1a, 0x50, 0xfa, 0x05, 0x69, 0x63, 0xa1, 0x88, 0x34, 0x45, 0x6b, 0x23, 0x8e, 0xc8, 0xd8, 0xab,
	0xca, 0xaa, 0xe3, 0x85, 0xdd, 0xf5, 0x77, 0x80, 0xc4, 0x8f, 0x22, 0xf1, 0x03, 0xc8, 0x6b, 0xbb,
	0x4d, 0x15, 0x38, 0x22, 0xe5, 0x38, 0xf3, 0xde, 0xbe, 0x37, 0x63, 0xbd, 0x31, 0x78, 0x5c, 0x56,
	0x46, 0xa8, 0xf9, 0x57, 0x25, 0x8d, 0x44, 0xba, 0x13, 0x46, 0xc9, 0x73, 0x28, 0x64, 0x2a, 0x9b,
	0x16, 0x7b, 0x09, 0x34, 0x96, 0xf7, 0xa2, 0xc4, 0x09, 0xf4, 0xf3, 0x2c, 0x20, 0x53, 0x32, 0x1b,
	0xf1, 0x7e, 0x9e, 0xb1, 0x0f, 0xe0, 0x45, 0x26, 0x51, 0x86, 0x8b, 0x6f, 0x95, 0xd0, 0x06, 0x67,
	0xe0, 0x6a, 0x93, 0x98, 0x5c, 0x96, 0x41, 0x7f, 0x4a, 0x66, 0xe3, 0xc5, 0x64, 0x6e, 0xd5, 0xe6,
	0x51, 0xd3, 0xe5, 0x1d, 0x8c, 0x67, 0xe0, 0x54, 0x5a, 0xa8, 0xf5, 0x2a, 0x18, 0x58, 0xb5, 0xb6,
	0x62, 0xdf, 0x09, 0x8c, 0x37, 0x79, 0x79, 0xdf, 0x29, 0x32, 0xa0, 0xa6, 0xb6, 0xb6, 0xa6, 0xe3,
	0x85, 0xd7, 0xea, 0xd9, 0x71, 0x78, 0x03, 0xe1, 0x14, 0x06, 0x5a, 0xa5, 0xff, 0x70, 0xac, 0xa1,
	0x9a, 0x91, 0x69, 0x63, 0xad, 0xfe, 0xc2, 0xc8, 0xb4, 0xc1, 0x00, 0xdc, 0x9d, 0xd0, 0x3a, 0xb9,
	0x13, 0xc1, 0xd0, 0x0e, 0xd4, 0x95, 0xec, 0x07, 0x01, 0xef, 0xaa, 0x90, 0xe9, 0x11, 0x8d, 0xf4,
	0x93, 0xc0, 0xb3, 0x58, 0x25, 0xa5, 0xde, 0xe5, 0xe6, 0x78, 0xa6, 0xfa, 0x45, 0xc0, 0x89, 0xf2,
	0xbb, 0x32, 0x29, 0xfe, 0xaf, 0x11, 0xbe, 0x01, 0x37, 0x95, 0xa5, 0x51, 0xb2, 0x08, 0xe8, 0x94,
	0xcc, 0x26, 0x8b, 0x17, 0xdd, 0x7b, 0xeb, 0x3e, 0xbf, 0x6e, 0x40, 0xde, 0xb1, 0xd8, 0x27, 0x70,
	0xdb, 0x1e, 0x7a, 0x70, 0xb2, 0xbd, 0x8d, 0x3f, 0x7f, 0x8c, 0xc2, 0x95, 0xdf, 0xc3, 0x11, 0xd0,
	0x28, 0x5e, 0xf2, 0xd8, 0x27, 0x78, 0x0a, 0xa3, 0x38, 0xe4, 0x37, 0xeb, 0xed, 0x32, 0x0e, 0xfd,
	0x3e, 0x02, 0x38, 0x9b, 0xf5, 0xf6, 0x7d, 0xb8, 0xf2, 0x07, 0x38, 0x06, 0xf7, 0x26, 0x8c, 0xa2,
	0xe5, 0xbb, 0xd0, 0x1f, 0xd6, 0xc5, 0xd5, 0xe6, 0xf6, 0xba, 0x46, 0xe8, 0xe2, 0x37, 0x01, 0xa7,
	0x39, 0x1e, 0xbc, 0x00, 0x6a, 0x4f, 0x01, 0x9f, 0x3f, 0x2e, 0xf3, 0x70, 0x18, 0xe7, 0xa7, 0x7b,
	0x1b, 0x56, 0x9a, 0xf5, 0xf0, 0x35, 0x0c, 0xeb, 0x98, 0x23, 0xb6, 0xc0, 0x5e, 0xe6, 0x0f, 0xc9,
	0x17, 0x40, 0x6d, 0x02, 0x1f, 0xb4, 0xf7, 0xf3, 0x78, 0x48, 0xbf, 0x84, 0x93, 0x2e, 0x1d, 0x78,
	0xd6, 0xe5, 0xe0, 0x69, 0x5c, 0x0e, 0x1f, 0xbd, 0x02, 0x67, 0x93, 0x6b, 0x23, 0x4a, 0x7c, 0x12,
	0x9d, 0x47, 0xa2, 0xfd, 0xb6, 0xac, 0xf7, 0x96, 0x7c, 0x71, 0xec, 0x5f, 0xe1, 0xf2, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0xac, 0xa8, 0x43, 0x38, 0x04, 0x00, 0x00,
}
