// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Ctl.proto

package metro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CtlClient is the client API for Ctl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CtlClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Status, error)
}

type ctlClient struct {
	cc *grpc.ClientConn
}

func NewCtlClient(cc *grpc.ClientConn) CtlClient {
	return &ctlClient{cc}
}

func (c *ctlClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/metro.Ctl/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CtlServer is the server API for Ctl service.
type CtlServer interface {
	Start(context.Context, *StartRequest) (*Status, error)
}

func RegisterCtlServer(s *grpc.Server, srv CtlServer) {
	s.RegisterService(&_Ctl_serviceDesc, srv)
}

func _Ctl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CtlServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metro.Ctl/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CtlServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ctl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metro.Ctl",
	HandlerType: (*CtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Ctl_Start_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ctl.proto",
}

func init() { proto.RegisterFile("Ctl.proto", fileDescriptor_Ctl_ee8fe01a513dd9c5) }

var fileDescriptor_Ctl_ee8fe01a513dd9c5 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x74, 0x2e, 0xc9, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4d, 0x2d, 0x29, 0xca, 0x97, 0xe2, 0xca, 0xc9,
	0x4f, 0xce, 0x87, 0x08, 0x19, 0x99, 0x70, 0x31, 0x3b, 0x97, 0xe4, 0x08, 0xe9, 0x72, 0xb1, 0x06,
	0x97, 0x24, 0x16, 0x95, 0x08, 0x09, 0xeb, 0x81, 0xd5, 0xe8, 0x81, 0x79, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x52, 0xbc, 0x08, 0xc1, 0x92, 0xd2, 0x62, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x66,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0xd0, 0x3b, 0xdf, 0x5c, 0x00, 0x00, 0x00,
}
