// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loco.proto

package metro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Station struct {
	// flow id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_loco_2412cb629f97020d, []int{0}
}
func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (dst *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(dst, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_loco_2412cb629f97020d, []int{1}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type StartRequest struct {
	// required(image)
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_loco_2412cb629f97020d, []int{2}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *StartRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Station)(nil), "metro.Station")
	proto.RegisterType((*Status)(nil), "metro.Status")
	proto.RegisterType((*StartRequest)(nil), "metro.StartRequest")
}

func init() { proto.RegisterFile("loco.proto", fileDescriptor_loco_2412cb629f97020d) }

var fileDescriptor_loco_2412cb629f97020d = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xb1, 0x0e, 0x82, 0x40,
	0x10, 0x44, 0x03, 0x0a, 0xc4, 0xd5, 0x50, 0x6c, 0x8c, 0xa1, 0xb0, 0x30, 0x54, 0x54, 0x14, 0xfa,
	0x09, 0xda, 0xd8, 0x99, 0xe3, 0x0b, 0x4e, 0xd8, 0x98, 0x4b, 0x84, 0xd5, 0xbb, 0xe5, 0xff, 0x0d,
	0x0b, 0x76, 0x33, 0x73, 0xb9, 0x37, 0xb3, 0x00, 0x6f, 0x6e, 0xb9, 0xfe, 0x78, 0x16, 0xc6, 0xa4,
	0x27, 0xf1, 0x5c, 0x5e, 0x21, 0x6b, 0xc4, 0x8a, 0xe3, 0x01, 0x73, 0x88, 0x5d, 0x57, 0x44, 0xa7,
	0xa8, 0xda, 0x98, 0xd8, 0x75, 0x88, 0xb0, 0x1e, 0x6c, 0x4f, 0x45, 0xac, 0x89, 0x6a, 0xdc, 0x43,
	0xe2, 0x7a, 0xfb, 0xa2, 0x62, 0xa5, 0xe1, 0x6c, 0xca, 0x23, 0xa4, 0x13, 0x64, 0x0c, 0xd3, 0x9f,
	0x96, 0x3b, 0x52, 0x4a, 0x62, 0x54, 0x97, 0x0f, 0xd8, 0x35, 0x62, 0xbd, 0x18, 0xfa, 0x8e, 0x14,
	0x04, 0x2b, 0xc8, 0xc2, 0x5c, 0xa9, 0xe8, 0xed, 0x39, 0xaf, 0x75, 0x4b, 0xbd, 0x0c, 0x31, 0xff,
	0x67, 0x3c, 0x40, 0x3a, 0x06, 0xf2, 0xf7, 0xdb, 0x52, 0xb7, 0xb8, 0x67, 0xaa, 0x27, 0x5c, 0x7e,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x85, 0x91, 0x87, 0xd0, 0x00, 0x00, 0x00,
}
